name: Docker Image CI

on:
  push:
    branches:
      - master
      - practice-deployment

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and push image
      id: build-image
      working-directory: ./azure-vote
      run: |
           az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-vote-front:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .